language: java
jdk:
  - oraclejdk7
services:
  - mysql
  - postgresql
before_install:
  - sudo rm /etc/mavenrc
  - psql -U postgres < ./flyway-core/src/test/resources/migration/dbsupport/postgresql/createDatabase.sql
  - mysql --verbose -uroot < ./flyway-core/src/test/resources/migration/dbsupport/mysql/createDatabase.sql
  - echo "mariadb.url=jdbc:mariadb://localhost/flyway_maria_db" > ~/flyway-mediumtests.properties
install: "sh ./mvnw -Dmaven.repo.local=~/.m2/repository verify -P-CommercialDBTest -P-CommandlinePlatformAssemblies"